name: "Commit git changes"
description: "Commit git changes directly to GitHub using the GraphQL API"
author: "step-security"

branding:
  color: "orange"
  icon: "git-commit"

inputs:
  commit_message:
    description: The commit message to use.
    required: true
  repo:
    description: The name of the repo to commit to in "owner/repo" format.
    required: true
  branch:
    description: The name of the branch to commit to.
    required: true
  empty:
    description: Allow making an empty commit if there are no changes.
    required: false
    default: "false"
  file_pattern:
    description: File pattern used for `git add`. For example `src/*.js`
    required: false
    default: "."

outputs:
  commit-url:
    description: The URL of the created commit.
  commit-hash:
    description: The hash of the created commit.

runs:
  using: "docker"
  image: "docker://ghcr.io/step-security/ghcommit-action:v0.2.21@sha256:c10619a1636f97162ce35ce303077aedb8c67b3e3701b89d1b830adaca062685" #v0.2.21
  args:
    - ${{ inputs.commit_message }}
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
    - ${{ inputs.empty }}
    - ${{ inputs.file_pattern }}
